name: PR build test

on:
  pull_request:
    branches:
      - main

jobs:
  test_build:
    name: Test build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.14'

    - name: Install Dependencies
      run: yarn

    - name: Build
      run: yarn build
